name: .NET Core xUnit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # Use the latest Windows environment

    env:
      Solution_Name: your-solution-name                        # The solution name, e.g., MyProject.sln
      Test_Project_Path: your-test-project-path                # The path to your xUnit test project, e.g., MyProject.Tests/MyProject.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure all history is fetched so that tests are correctly discovered

    # Set up .NET SDK
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # Ensure the correct .NET version is installed

    # Restore dependencies for the test project
    - name: Restore dependencies
      run: dotnet restore $env:Test_Project_Path --configuration ${{ matrix.configuration }}

    # Build the test project (optional, but ensures everything is built before testing)
    - name: Build the project
      run: dotnet build $env:Test_Project_Path --configuration ${{ matrix.configuration }}

    # Run unit tests using xUnit
    - name: Run unit tests
      run: dotnet test $env:Test_Project_Path --configuration ${{ matrix.configuration }}

